# Data Preparation 6

In [83]:
import pandas as pd
from IPython.display import display
import numpy as np
import sqlite3
pd.options.display.max_columns = None
pd.options.display.max_rows = 200

In [84]:
admissions=pd.read_csv('MAIN_DF_5.csv')
admissions=admissions.drop(['Unnamed: 0'], axis=1)
admissions=admissions.reset_index(drop=True)
print(admissions.shape)
print('unique SUBJECT_ID:', admissions.SUBJECT_ID.nunique())
print('unique HADM_ID   :', admissions.HADM_ID.nunique())
print('unique ICUSTAY_ID:', admissions.ICUSTAY_ID.nunique())
admissions.head()

(48989, 183)
unique SUBJECT_ID: 36659
unique HADM_ID   : 46273
unique ICUSTAY_ID: 48989

,SUBJECT_ID,HADM_ID,ICUSTAY_ID,GENDER,AGE_AD,ADMITTIME,DISCHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,ETHNICITY,DIAGNOSIS,DBSOURCE,FIRST_CAREUNIT,LAST_CAREUNIT,INTIME,OUTTIME,LOS,LOS_C,TIMEDELTA,TIMEDELTA_C,HOSPITAL_EXPIRE_FLAG,HEIGHT,WEIGHT,BMI,I_VEN,NI_VEN,227456_T,227456_V,227456_U,225624_T,225624_V,225624_U,220615_T,220615_V,220615_U,225651_T,225651_V,225651_U,220621_T,220621_V,220621_U,226537_T,226537_V,226537_U,228388_T,228388_V,228388_U,225664_T,225664_V,225664_U,220545_T,220545_V,220545_U,226540_T,226540_V,226540_U,225668_T,225668_V,225668_U,220235_T,220235_V,220235_U,226062_T,226062_V,226062_U,223830_T,223830_V,223830_U,220734_T,220734_V,220734_U,228243_T,228243_V,228243_U,220274_T,220274_V,220274_U,227457_T,227457_V,227457_U,220224_T,220224_V,220224_U,227516_T,227516_V,227516_U,226063_T,226063_V,226063_U,220227_T,220227_V,220227_U,220645_T,220645_V,220645_U,228389_T,228389_V,228389_U,226534_T,226534_V,226534_U,228390_T,228390_V,228390_U,225690_T,225690_V,225690_U,220546_T,220546_V,220546_U,220574_T,220574_V,220574_U,225678_T,225678_V,225678_U,220739_T,220739_V,220739_U,223901_T,223901_V,223901_U,223900_T,223900_V,223900_U,223835_T,223835_V,223835_U,224688_T,224688_V,224688_U,224689_T,224689_V,224689_U,224690_T,224690_V,224690_U,220210_T,220210_V,220210_U,220277_T,220277_V,220277_U,220051_T,220051_V,220051_U,220052_T,220052_V,220052_U,220050_T,220050_V,220050_U,220045_T,220045_V,220045_U,224643_T,224643_V,224643_U,227242_T,227242_V,227242_U,224167_T,224167_V,224167_U,227243_T,227243_V,227243_U,220180_T,220180_V,220180_U,220181_T,220181_V,220181_U,220179_T,220179_V,220179_U,223761_T,223761_V,223761_U,224027_T,224027_V,224027_U
0,3,145834,211552,M,76.53,2101-10-20 19:08:00,2101-10-31 13:58:00,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,WHITE,HYPOTENSION,carevue,MICU,MICU,2101-10-20 19:10:11,2101-10-26 20:43:09,6.0646,>4,10.78,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,185777,294638,F,47.84,2191-03-16 00:28:00,2191-03-23 18:41:00,EMERGENCY,EMERGENCY ROOM ADMIT,Private,WHITE,"FEVER,DEHYDRATION,FAILURE TO THRIVE",carevue,MICU,MICU,2191-03-16 00:29:31,2191-03-17 16:46:31,1.6785,1-2,7.76,6-10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,107064,228232,F,65.94,2175-05-30 07:15:00,2175-06-15 16:00:00,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,WHITE,CHRONIC RENAL FAILURE/SDA,carevue,SICU,SICU,2175-05-30 21:30:54,2175-06-03 13:39:54,3.6729,2-4,16.36,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,150750,220597,M,41.79,2149-11-09 13:06:00,2149-11-14 10:15:00,EMERGENCY,EMERGENCY ROOM ADMIT,Medicaid,NW,HEMORRHAGIC CVA,carevue,MICU,MICU,2149-11-09 13:07:02,2149-11-14 20:52:14,5.3231,>4,4.88,3-6,1,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,194540,229441,F,50.15,2178-04-16 06:18:00,2178-05-11 19:00:00,EMERGENCY,EMERGENCY ROOM ADMIT,Private,WHITE,BRAIN MASS,carevue,SICU,SICU,2178-04-16 06:19:32,2178-04-17 20:21:05,1.5844,1-2,25.53,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
admissions['DBSOURCE'].value_counts()

carevue       26646
metavision    22245
both             98
Name: DBSOURCE, dtype: int64

Check coherence in variable units

In [86]:
for j in range(182,28,-3):
    print(j, admissions[admissions.columns[j]].value_counts(), '\t')

182 Series([], Name: 224027_U, dtype: int64)
179 ?F    21809
Name: 223761_U, dtype: int64
176 mmHg    21813
Name: 220179_U, dtype: int64
173 mmHg    21806
Name: 220181_U, dtype: int64
170 mmHg    21813
Name: 220180_U, dtype: int64
167 mmHg    391
Name: 227243_U, dtype: int64
164 mmHg    435
Name: 224167_U, dtype: int64
161 mmHg    363
Name: 227242_U, dtype: int64
158 mmHg    418
Name: 224643_U, dtype: int64
155 bpm    22081
Name: 220045_U, dtype: int64
152 mmHg    8815
Name: 220050_U, dtype: int64
149 mmHg    8913
Name: 220052_U, dtype: int64
146 mmHg    8822
Name: 220051_U, dtype: int64
143 %    22061
Name: 220277_U, dtype: int64
140 insp/min    22069
Name: 220210_U, dtype: int64
137 insp/min    9040
Name: 224690_U, dtype: int64
134 insp/min    9258
Name: 224689_U, dtype: int64
131 insp/min    8526
Name: 224688_U, dtype: int64
128 Series([], Name: 223835_U, dtype: int64)
125 Series([], Name: 223900_U, dtype: int64)
122 Series([], Name: 223901_U, dtype: int64)
119 Series([], Name: 220739_U, dtype: int64)
116 Series([], Name: 225678_U, dtype: int64)
113 Series([], Name: 220574_U, dtype: int64)
110 K/uL    24032
Name: 220546_U, dtype: int64
107 mg/dL    10760
Name: 225690_U, dtype: int64
104 Series([], Name: 228390_U, dtype: int64)
101 mEq/L    5809
Name: 226534_U, dtype: int64
98 Series([], Name: 228389_U, dtype: int64)
95 mEq/L    24120
Name: 220645_U, dtype: int64
92 %    6414
Name: 220227_U, dtype: int64
89 mmHg    1880
Name: 226063_U, dtype: int64
86 mmHg    1218
Name: 227516_U, dtype: int64
83 mmHg    12374
Name: 220224_U, dtype: int64
80 K/uL    24038
Name: 227457_U, dtype: int64
77 units    3801
Name: 220274_U, dtype: int64
74 Series([], Name: 228243_U, dtype: int64)
71 units    9278
Name: 220734_U, dtype: int64
68 units    12436
Name: 223830_U, dtype: int64
65 mmHg    1882
Name: 226062_U, dtype: int64
62 mmHg    12375
Name: 220235_U, dtype: int64
59 mmol/L    13009
Name: 225668_U, dtype: int64
56 %    5530
Name: 226540_U, dtype: int64
53 %    24086
Name: 220545_U, dtype: int64
50 Series([], Name: 225664_U, dtype: int64)
47 Series([], Name: 228388_U, dtype: int64)
44 mg/dL    7120
Name: 226537_U, dtype: int64
41 mg/dL    24031
Name: 220621_U, dtype: int64
38 mg/dL    1320
Name: 225651_U, dtype: int64
35 mg/dL    24112
Name: 220615_U, dtype: int64
32 mg/dL    24119
Name: 225624_U, dtype: int64
29 g/dL    8848
Name: 227456_U, dtype: int64

In [87]:
cols = [i for i in range(182,28,-3)]
admissions.drop(admissions.columns[cols],axis=1,inplace=True)
admissions.shape

(48989, 131)

In [88]:
#care=admissions[admissions['DBSOURCE']=='carevue']
#care.isnull().sum().sum()/(care.shape[0]*care.shape[1])
#meta=admissions[admissions['DBSOURCE']=='metavision']
#meta.isnull().sum().sum()/(meta.shape[0]*meta.shape[1])
#print(care.shape)
#print(meta.shape)

In [89]:
print(len(admissions.columns[admissions.isna().all()].tolist()))
admissions.columns[admissions.isna().all()].tolist()

12

['228388_T',
 '228388_V',
 '228243_T',
 '228243_V',
 '228389_T',
 '228389_V',
 '228390_T',
 '228390_V',
 '220574_T',
 '220574_V',
 '225678_T',
 '225678_V']

In [90]:
admissions=admissions.dropna(axis='columns', how='all')
admissions.shape

(48989, 119)

In [91]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
ADMISSION_LOCATION          0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
LAST_CAREUNIT               0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  33539
WEIGHT                  24452
BMI                     33658
I_VEN                       0
NI_VEN                      0
227456_T                40138
227456_V                40138
225624_T                24849
225624_V                24849
220615_T                24856
220615_V                24856
225651_T                47669
225651_V                47669
220621_T                24921
220621_V                24921
226537_T                41337
226537_V                41337
225664_T                32245
225664_V                32245
220545_T                24881
220545_V                24881
226540_T                43455
226540_V                43455
225668_T                35977
225668_V                35977
220235_T                36614
220235_V                36614
226062_T                47107
226062_V                47107
223830_T                36530
223830_V                36530
220734_T                39707
220734_V                39707
220274_T                45171
220274_V                45171
227457_T                24934
227457_V                24934
220224_T                36615
220224_V                36615
227516_T                47771
227516_V                47771
226063_T                47109
226063_V                47109
220227_T                42575
220227_V                42575
220645_T                24851
220645_V                24851
226534_T                43169
226534_V                43169
225690_T                38227
225690_V                38227
220546_T                24937
220546_V                24937
220739_T                26960
220739_V                26960
223901_T                26967
223901_V                26967
223900_T                26963
223900_V                26963
223835_T                37492
223835_V                37492
224688_T                40463
224688_V                40463
224689_T                39731
224689_V                39731
224690_T                39949
224690_V                39949
220210_T                26920
220210_V                26920
220277_T                26928
220277_V                26928
220051_T                40167
220051_V                40167
220052_T                40076
220052_V                40076
220050_T                40174
220050_V                40174
220045_T                26908
220045_V                26908
224643_T                48571
224643_V                48571
227242_T                48626
227242_V                48626
224167_T                48554
224167_V                48554
227243_T                48598
227243_V                48598
220180_T                27176
220180_V                27176
220181_T                27183
220181_V                27183
220179_T                27176
220179_V                27176
223761_T                27180
223761_V                27180
224027_T                27039
224027_V                27039
dtype: int64

In [92]:
admissions.shape

(48989, 119)

In [93]:
admissions = admissions.loc[:, admissions.isnull().mean() < .9]

In [94]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
ADMISSION_LOCATION          0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
LAST_CAREUNIT               0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  33539
WEIGHT                  24452
BMI                     33658
I_VEN                       0
NI_VEN                      0
227456_T                40138
227456_V                40138
225624_T                24849
225624_V                24849
220615_T                24856
220615_V                24856
220621_T                24921
220621_V                24921
226537_T                41337
226537_V                41337
225664_T                32245
225664_V                32245
220545_T                24881
220545_V                24881
226540_T                43455
226540_V                43455
225668_T                35977
225668_V                35977
220235_T                36614
220235_V                36614
223830_T                36530
223830_V                36530
220734_T                39707
220734_V                39707
227457_T                24934
227457_V                24934
220224_T                36615
220224_V                36615
220227_T                42575
220227_V                42575
220645_T                24851
220645_V                24851
226534_T                43169
226534_V                43169
225690_T                38227
225690_V                38227
220546_T                24937
220546_V                24937
220739_T                26960
220739_V                26960
223901_T                26967
223901_V                26967
223900_T                26963
223900_V                26963
223835_T                37492
223835_V                37492
224688_T                40463
224688_V                40463
224689_T                39731
224689_V                39731
224690_T                39949
224690_V                39949
220210_T                26920
220210_V                26920
220277_T                26928
220277_V                26928
220051_T                40167
220051_V                40167
220052_T                40076
220052_V                40076
220050_T                40174
220050_V                40174
220045_T                26908
220045_V                26908
220180_T                27176
220180_V                27176
220181_T                27183
220181_V                27183
220179_T                27176
220179_V                27176
223761_T                27180
223761_V                27180
224027_T                27039
224027_V                27039
dtype: int64

In [95]:
admissions.shape

(48989, 101)

In [96]:
cols = [i for i in range(99,26,-2)]
admissions.drop(admissions.columns[cols],axis=1,inplace=True)
admissions.shape

(48989, 64)

In [97]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
ADMISSION_LOCATION          0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
LAST_CAREUNIT               0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  33539
WEIGHT                  24452
BMI                     33658
I_VEN                       0
NI_VEN                      0
227456_V                40138
225624_V                24849
220615_V                24856
220621_V                24921
226537_V                41337
225664_V                32245
220545_V                24881
226540_V                43455
225668_V                35977
220235_V                36614
223830_V                36530
220734_V                39707
227457_V                24934
220224_V                36615
220227_V                42575
220645_V                24851
226534_V                43169
225690_V                38227
220546_V                24937
220739_V                26960
223901_V                26967
223900_V                26963
223835_V                37492
224688_V                40463
224689_V                39731
224690_V                39949
220210_V                26920
220277_V                26928
220051_V                40167
220052_V                40076
220050_V                40174
220045_V                26908
220180_V                27176
220181_V                27183
220179_V                27176
223761_V                27180
224027_V                27039
dtype: int64

In [98]:
admissions.to_csv('MAIN_DF_6.csv')

In [14]:
#admissions.dropna(thresh=110).shape

In [74]:
connex = sqlite3.connect("data/CHARTEVENTS.db")
cur = connex.cursor()

In [76]:
#ids = [items.ITEMID[70]]
ids=[220050]
ids = [str(id) for id in ids] 
str_matching = "(" + ",".join(ids) + ")"
sql = "SELECT * FROM CHARTEVENTS_DB WHERE ITEMID IN " + str_matching + ";"
print('String of SQL:', sql)
df=pd.read_sql_query(sql, connex)
df=df[df['ERROR']==0]
df=df.drop(['ROW_ID', 'ITEMID', 'STORETIME', 'CGID', 'VALUENUM', 'WARNING', 
                                'ERROR', 'RESULTSTATUS', 'STOPPED'], axis=1)
#df=df.rename({'CHARTTIME':'T_ABPD', 'VALUE':'ABPD'}, axis='columns')
print(df.shape)
print('unique ICUSTAY_ID:', df.ICUSTAY_ID.nunique())
df.head()
#df=df.sort_values(by=['T_ABPD'])
#df=df.drop_duplicates('ICUSTAY_ID')
#admissions=pd.merge(admissions,df,how='left',on=['SUBJECT_ID', 'HADM_ID','ICUSTAY_ID'])
#print(admissions.shape)

String of SQL: SELECT * FROM CHARTEVENTS_DB WHERE ITEMID IN (220050);
(1147386, 6)
unique ICUSTAY_ID: 9851

   SUBJECT_ID  HADM_ID  ICUSTAY_ID            CHARTTIME  VALUE VALUEUOM
0          23   124321    234044.0  2157-10-22 11:00:00  128.0     mmHg
1          23   124321    234044.0  2157-10-22 12:00:00  144.0     mmHg
2          23   124321    234044.0  2157-10-22 13:00:00  118.0     mmHg
3          23   124321    234044.0  2157-10-22 14:00:00  124.0     mmHg
4          23   124321    234044.0  2157-10-22 15:00:00  135.0     mmHg

In [ ]:
database_file = 'CHARTEVENTS_DB'
database_loc  = 'data/CHARTEVENTS.db'
ids =

In [ ]:
def get_pd(database_file, database_loc, ids, admissions):
    connex = sqlite3.connect(database_loc)
    cur = connex.cursor()
    ids = str(ids)
    str_matching = "(" + ids + ")"
    sql = "SELECT * FROM " + database_file + " WHERE ITEMID IN " + str_matching + ";"
    print('String of SQL:', sql)
    cur.execute(sql)
    df=pd.read_sql_query(sql, connex)
    df=df[df['ERROR']==0]
    df=df.drop(['ROW_ID', 'ITEMID', 'STORETIME', 'CGID', 'VALUENUM', 'WARNING', 
                                'ERROR', 'RESULTSTATUS', 'STOPPED'], axis=1)
    df=df.rename({'CHARTTIME':ids + '_T', 'VALUE':ids + '_V', 'VALUEUOM':ids + '_U'}, axis='columns')
    df=df.sort_values(by=[ids + '_T'])
    df=df.drop_duplicates('ICUSTAY_ID')
    admissions=pd.merge(admissions,df,how='left',on=['SUBJECT_ID','HADM_ID','ICUSTAY_ID'])
    a=pd.to_datetime(admissions[ids + '_T'])-pd.to_datetime(admissions.INTIME)
    admissions[ids + '_T']=np.round(a.dt.total_seconds()/86400, 2)
    cur.close()
    connex.close()
    return admissions

In [ ]:
admissions=get_pd(database_file, database_loc, ids, admissions)