# Data Preparation 6

In [46]:
import pandas as pd
from IPython.display import display
import numpy as np
import sqlite3
pd.options.display.max_columns = None
pd.options.display.max_rows = 200

In [47]:
admissions=pd.read_csv('MAIN_DF_5.csv')
admissions=admissions.drop(['Unnamed: 0'], axis=1)
admissions=admissions.reset_index(drop=True)
print(admissions.shape)
print('unique SUBJECT_ID:', admissions.SUBJECT_ID.nunique())
print('unique HADM_ID   :', admissions.HADM_ID.nunique())
print('unique ICUSTAY_ID:', admissions.ICUSTAY_ID.nunique())
admissions.head()

(51518, 182)
unique SUBJECT_ID: 37778
unique HADM_ID   : 48372
unique ICUSTAY_ID: 51518

,SUBJECT_ID,HADM_ID,ICUSTAY_ID,GENDER,AGE_AD,ADMITTIME,DISCHTIME,ADMISSION_TYPE,INSURANCE,ETHNICITY,DIAGNOSIS,DBSOURCE,FIRST_CAREUNIT,FIRST_WARDID,INTIME,OUTTIME,LOS,LOS_C,TIMEDELTA,TIMEDELTA_C,HOSPITAL_EXPIRE_FLAG,HEIGHT,WEIGHT,BMI,I_VEN,NI_VEN,227456_T,227456_V,227456_U,225624_T,225624_V,225624_U,220615_T,220615_V,220615_U,225651_T,225651_V,225651_U,220621_T,220621_V,220621_U,226537_T,226537_V,226537_U,228388_T,228388_V,228388_U,225664_T,225664_V,225664_U,220545_T,220545_V,220545_U,226540_T,226540_V,226540_U,225668_T,225668_V,225668_U,220235_T,220235_V,220235_U,226062_T,226062_V,226062_U,223830_T,223830_V,223830_U,220734_T,220734_V,220734_U,228243_T,228243_V,228243_U,220274_T,220274_V,220274_U,227457_T,227457_V,227457_U,220224_T,220224_V,220224_U,227516_T,227516_V,227516_U,226063_T,226063_V,226063_U,220227_T,220227_V,220227_U,220645_T,220645_V,220645_U,228389_T,228389_V,228389_U,226534_T,226534_V,226534_U,228390_T,228390_V,228390_U,225690_T,225690_V,225690_U,220546_T,220546_V,220546_U,220574_T,220574_V,220574_U,225678_T,225678_V,225678_U,220739_T,220739_V,220739_U,223901_T,223901_V,223901_U,223900_T,223900_V,223900_U,223835_T,223835_V,223835_U,224688_T,224688_V,224688_U,224689_T,224689_V,224689_U,224690_T,224690_V,224690_U,220210_T,220210_V,220210_U,220277_T,220277_V,220277_U,220051_T,220051_V,220051_U,220052_T,220052_V,220052_U,220050_T,220050_V,220050_U,220045_T,220045_V,220045_U,224643_T,224643_V,224643_U,227242_T,227242_V,227242_U,224167_T,224167_V,224167_U,227243_T,227243_V,227243_U,220180_T,220180_V,220180_U,220181_T,220181_V,220181_U,220179_T,220179_V,220179_U,223761_T,223761_V,223761_U,224027_T,224027_V,224027_U
0,3,145834,211552,M,76.53,2101-10-20 19:08:00,2101-10-31 13:58:00,EMERGENCY,Medicare,WHITE,HYPOTENSION,carevue,MICU,12,2101-10-20 19:10:11,2101-10-26 20:43:09,6.0646,>4,10.78,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,185777,294638,F,47.84,2191-03-16 00:28:00,2191-03-23 18:41:00,EMERGENCY,Private,WHITE,"FEVER,DEHYDRATION,FAILURE TO THRIVE",carevue,MICU,52,2191-03-16 00:29:31,2191-03-17 16:46:31,1.6785,1-2,7.76,6-10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,107064,228232,F,65.94,2175-05-30 07:15:00,2175-06-15 16:00:00,ELECTIVE,Medicare,WHITE,CHRONIC RENAL FAILURE/SDA,carevue,SICU,33,2175-05-30 21:30:54,2175-06-03 13:39:54,3.6729,2-4,16.36,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,150750,220597,M,41.79,2149-11-09 13:06:00,2149-11-14 10:15:00,EMERGENCY,Medicaid,NW,HEMORRHAGIC CVA,carevue,MICU,15,2149-11-09 13:07:02,2149-11-14 20:52:14,5.3231,>4,4.88,3-6,1,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,194540,229441,F,50.15,2178-04-16 06:18:00,2178-05-11 19:00:00,EMERGENCY,Private,WHITE,BRAIN MASS,carevue,SICU,57,2178-04-16 06:19:32,2178-04-17 20:21:05,1.5844,1-2,25.53,>10,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
admissions['DBSOURCE'].value_counts()

carevue       28350
metavision    23055
both            113
Name: DBSOURCE, dtype: int64

Check coherence in variable units

In [49]:
for j in range(181,27,-3):
    print(j, admissions[admissions.columns[j]].value_counts(), '\t')

181 Series([], Name: 224027_U, dtype: int64)
178 ?F    22586
Name: 223761_U, dtype: int64
175 mmHg    22587
Name: 220179_U, dtype: int64
172 mmHg    22580
Name: 220181_U, dtype: int64
169 mmHg    22587
Name: 220180_U, dtype: int64
166 mmHg    424
Name: 227243_U, dtype: int64
163 mmHg    474
Name: 224167_U, dtype: int64
160 mmHg    392
Name: 227242_U, dtype: int64
157 mmHg    454
Name: 224643_U, dtype: int64
154 bpm    22864
Name: 220045_U, dtype: int64
151 mmHg    9421
Name: 220050_U, dtype: int64
148 mmHg    9523
Name: 220052_U, dtype: int64
145 mmHg    9428
Name: 220051_U, dtype: int64
142 %    22843
Name: 220277_U, dtype: int64
139 insp/min    22852
Name: 220210_U, dtype: int64
136 insp/min    9656
Name: 224690_U, dtype: int64
133 insp/min    9882
Name: 224689_U, dtype: int64
130 insp/min    9142
Name: 224688_U, dtype: int64
127 Series([], Name: 223835_U, dtype: int64)
124 Series([], Name: 223900_U, dtype: int64)
121 Series([], Name: 223901_U, dtype: int64)
118 Series([], Name: 220739_U, dtype: int64)
115 Series([], Name: 225678_U, dtype: int64)
112 Series([], Name: 220574_U, dtype: int64)
109 K/uL    24895
Name: 220546_U, dtype: int64
106 mg/dL    11502
Name: 225690_U, dtype: int64
103 Series([], Name: 228390_U, dtype: int64)
100 mEq/L    6220
Name: 226534_U, dtype: int64
97 Series([], Name: 228389_U, dtype: int64)
94 mEq/L    24981
Name: 220645_U, dtype: int64
91 %    6964
Name: 220227_U, dtype: int64
88 mmHg    2094
Name: 226063_U, dtype: int64
85 mmHg    1398
Name: 227516_U, dtype: int64
82 mmHg    13126
Name: 220224_U, dtype: int64
79 K/uL    24902
Name: 227457_U, dtype: int64
76 units    4137
Name: 220274_U, dtype: int64
73 Series([], Name: 228243_U, dtype: int64)
70 units    9987
Name: 220734_U, dtype: int64
67 units    13187
Name: 223830_U, dtype: int64
64 mmHg    2097
Name: 226062_U, dtype: int64
61 mmHg    13126
Name: 220235_U, dtype: int64
58 mmol/L    13771
Name: 225668_U, dtype: int64
55 %    5900
Name: 226540_U, dtype: int64
52 %    24947
Name: 220545_U, dtype: int64
49 Series([], Name: 225664_U, dtype: int64)
46 Series([], Name: 228388_U, dtype: int64)
43 mg/dL    7639
Name: 226537_U, dtype: int64
40 mg/dL    24892
Name: 220621_U, dtype: int64
37 mg/dL    1549
Name: 225651_U, dtype: int64
34 mg/dL    24975
Name: 220615_U, dtype: int64
31 mg/dL    24982
Name: 225624_U, dtype: int64
28 g/dL    9570
Name: 227456_U, dtype: int64

In [50]:
cols = [i for i in range(181,27,-3)]
admissions.drop(admissions.columns[cols],axis=1,inplace=True)
admissions.shape

(51518, 130)

In [51]:
#care=admissions[admissions['DBSOURCE']=='carevue']
#care.isnull().sum().sum()/(care.shape[0]*care.shape[1])
#meta=admissions[admissions['DBSOURCE']=='metavision']
#meta.isnull().sum().sum()/(meta.shape[0]*meta.shape[1])
#print(care.shape)
#print(meta.shape)

In [52]:
print(len(admissions.columns[admissions.isna().all()].tolist()))
admissions.columns[admissions.isna().all()].tolist()

12

['228388_T',
 '228388_V',
 '228243_T',
 '228243_V',
 '228389_T',
 '228389_V',
 '228390_T',
 '228390_V',
 '220574_T',
 '220574_V',
 '225678_T',
 '225678_V']

In [53]:
admissions=admissions.dropna(axis='columns', how='all')
admissions.shape

(51518, 118)

In [54]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
FIRST_WARDID                0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  35092
WEIGHT                  25880
BMI                     35164
I_VEN                       0
NI_VEN                      0
227456_T                41945
227456_V                41945
225624_T                26514
225624_V                26514
220615_T                26521
220615_V                26521
225651_T                49969
225651_V                49969
220621_T                26586
220621_V                26586
226537_T                43307
226537_V                43307
225664_T                34061
225664_V                34061
220545_T                26548
220545_V                26548
226540_T                45614
226540_V                45614
225668_T                37744
225668_V                37744
220235_T                38392
220235_V                38392
226062_T                49421
226062_V                49421
223830_T                38308
223830_V                38308
220734_T                41527
220734_V                41527
220274_T                47363
220274_V                47363
227457_T                26599
227457_V                26599
220224_T                38392
220224_V                38392
227516_T                50120
227516_V                50120
226063_T                49424
226063_V                49424
220227_T                44554
220227_V                44554
220645_T                26517
220645_V                26517
226534_T                45287
226534_V                45287
225690_T                40014
225690_V                40014
220546_T                26602
220546_V                26602
220739_T                28711
220739_V                28711
223901_T                28718
223901_V                28718
223900_T                28714
223900_V                28714
223835_T                39356
223835_V                39356
224688_T                42376
224688_V                42376
224689_T                41636
224689_V                41636
224690_T                41862
224690_V                41862
220210_T                28666
220210_V                28666
220277_T                28675
220277_V                28675
220051_T                42090
220051_V                42090
220052_T                41995
220052_V                41995
220050_T                42097
220050_V                42097
220045_T                28654
220045_V                28654
224643_T                51064
224643_V                51064
227242_T                51126
227242_V                51126
224167_T                51044
224167_V                51044
227243_T                51094
227243_V                51094
220180_T                28931
220180_V                28931
220181_T                28938
220181_V                28938
220179_T                28931
220179_V                28931
223761_T                28932
223761_V                28932
224027_T                28793
224027_V                28793
dtype: int64

In [55]:
admissions.shape

(51518, 118)

In [56]:
admissions.loc[:, admissions.isnull().mean() > .95].columns

Index(['225651_T', '225651_V', '226062_T', '226062_V', '227516_T', '227516_V',
       '226063_T', '226063_V', '224643_T', '224643_V', '227242_T', '227242_V',
       '224167_T', '224167_V', '227243_T', '227243_V'],
      dtype='object')

In [57]:
admissions = admissions.loc[:, admissions.isnull().mean() < .95]

In [58]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
FIRST_WARDID                0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  35092
WEIGHT                  25880
BMI                     35164
I_VEN                       0
NI_VEN                      0
227456_T                41945
227456_V                41945
225624_T                26514
225624_V                26514
220615_T                26521
220615_V                26521
220621_T                26586
220621_V                26586
226537_T                43307
226537_V                43307
225664_T                34061
225664_V                34061
220545_T                26548
220545_V                26548
226540_T                45614
226540_V                45614
225668_T                37744
225668_V                37744
220235_T                38392
220235_V                38392
223830_T                38308
223830_V                38308
220734_T                41527
220734_V                41527
220274_T                47363
220274_V                47363
227457_T                26599
227457_V                26599
220224_T                38392
220224_V                38392
220227_T                44554
220227_V                44554
220645_T                26517
220645_V                26517
226534_T                45287
226534_V                45287
225690_T                40014
225690_V                40014
220546_T                26602
220546_V                26602
220739_T                28711
220739_V                28711
223901_T                28718
223901_V                28718
223900_T                28714
223900_V                28714
223835_T                39356
223835_V                39356
224688_T                42376
224688_V                42376
224689_T                41636
224689_V                41636
224690_T                41862
224690_V                41862
220210_T                28666
220210_V                28666
220277_T                28675
220277_V                28675
220051_T                42090
220051_V                42090
220052_T                41995
220052_V                41995
220050_T                42097
220050_V                42097
220045_T                28654
220045_V                28654
220180_T                28931
220180_V                28931
220181_T                28938
220181_V                28938
220179_T                28931
220179_V                28931
223761_T                28932
223761_V                28932
224027_T                28793
224027_V                28793
dtype: int64

In [59]:
admissions.shape

(51518, 102)

In [60]:
cols = [i for i in range(100,27,-2)]
admissions.drop(admissions.columns[cols],axis=1,inplace=True)
admissions.shape

(51518, 65)

In [62]:
admissions.isnull().sum()

SUBJECT_ID                  0
HADM_ID                     0
ICUSTAY_ID                  0
GENDER                      0
AGE_AD                      0
ADMITTIME                   0
DISCHTIME                   0
ADMISSION_TYPE              0
INSURANCE                   0
ETHNICITY                   0
DIAGNOSIS                   0
DBSOURCE                    0
FIRST_CAREUNIT              0
FIRST_WARDID                0
INTIME                      0
OUTTIME                     0
LOS                         0
LOS_C                       0
TIMEDELTA                   0
TIMEDELTA_C                 0
HOSPITAL_EXPIRE_FLAG        0
HEIGHT                  35092
WEIGHT                  25880
BMI                     35164
I_VEN                       0
NI_VEN                      0
227456_T                41945
227456_V                41945
225624_V                26514
220615_V                26521
220621_V                26586
226537_V                43307
225664_V                34061
220545_V                26548
226540_V                45614
225668_V                37744
220235_V                38392
223830_V                38308
220734_V                41527
220274_V                47363
227457_V                26599
220224_V                38392
220227_V                44554
220645_V                26517
226534_V                45287
225690_V                40014
220546_V                26602
220739_V                28711
223901_V                28718
223900_V                28714
223835_V                39356
224688_V                42376
224689_V                41636
224690_V                41862
220210_V                28666
220277_V                28675
220051_V                42090
220052_V                41995
220050_V                42097
220045_V                28654
220180_V                28931
220181_V                28938
220179_V                28931
223761_V                28932
224027_V                28793
dtype: int64

In [63]:
admissions.to_csv('MAIN_DF_6.csv')

In [14]:
#admissions.dropna(thresh=110).shape

In [74]:
connex = sqlite3.connect("data/CHARTEVENTS.db")
cur = connex.cursor()

In [76]:
#ids = [items.ITEMID[70]]
ids=[220050]
ids = [str(id) for id in ids] 
str_matching = "(" + ",".join(ids) + ")"
sql = "SELECT * FROM CHARTEVENTS_DB WHERE ITEMID IN " + str_matching + ";"
print('String of SQL:', sql)
df=pd.read_sql_query(sql, connex)
df=df[df['ERROR']==0]
df=df.drop(['ROW_ID', 'ITEMID', 'STORETIME', 'CGID', 'VALUENUM', 'WARNING', 
                                'ERROR', 'RESULTSTATUS', 'STOPPED'], axis=1)
#df=df.rename({'CHARTTIME':'T_ABPD', 'VALUE':'ABPD'}, axis='columns')
print(df.shape)
print('unique ICUSTAY_ID:', df.ICUSTAY_ID.nunique())
df.head()
#df=df.sort_values(by=['T_ABPD'])
#df=df.drop_duplicates('ICUSTAY_ID')
#admissions=pd.merge(admissions,df,how='left',on=['SUBJECT_ID', 'HADM_ID','ICUSTAY_ID'])
#print(admissions.shape)

String of SQL: SELECT * FROM CHARTEVENTS_DB WHERE ITEMID IN (220050);
(1147386, 6)
unique ICUSTAY_ID: 9851

   SUBJECT_ID  HADM_ID  ICUSTAY_ID            CHARTTIME  VALUE VALUEUOM
0          23   124321    234044.0  2157-10-22 11:00:00  128.0     mmHg
1          23   124321    234044.0  2157-10-22 12:00:00  144.0     mmHg
2          23   124321    234044.0  2157-10-22 13:00:00  118.0     mmHg
3          23   124321    234044.0  2157-10-22 14:00:00  124.0     mmHg
4          23   124321    234044.0  2157-10-22 15:00:00  135.0     mmHg

In [ ]:
database_file = 'CHARTEVENTS_DB'
database_loc  = 'data/CHARTEVENTS.db'
ids =

In [ ]:
def get_pd(database_file, database_loc, ids, admissions):
    connex = sqlite3.connect(database_loc)
    cur = connex.cursor()
    ids = str(ids)
    str_matching = "(" + ids + ")"
    sql = "SELECT * FROM " + database_file + " WHERE ITEMID IN " + str_matching + ";"
    print('String of SQL:', sql)
    cur.execute(sql)
    df=pd.read_sql_query(sql, connex)
    df=df[df['ERROR']==0]
    df=df.drop(['ROW_ID', 'ITEMID', 'STORETIME', 'CGID', 'VALUENUM', 'WARNING', 
                                'ERROR', 'RESULTSTATUS', 'STOPPED'], axis=1)
    df=df.rename({'CHARTTIME':ids + '_T', 'VALUE':ids + '_V', 'VALUEUOM':ids + '_U'}, axis='columns')
    df=df.sort_values(by=[ids + '_T'])
    df=df.drop_duplicates('ICUSTAY_ID')
    admissions=pd.merge(admissions,df,how='left',on=['SUBJECT_ID','HADM_ID','ICUSTAY_ID'])
    a=pd.to_datetime(admissions[ids + '_T'])-pd.to_datetime(admissions.INTIME)
    admissions[ids + '_T']=np.round(a.dt.total_seconds()/86400, 2)
    cur.close()
    connex.close()
    return admissions

In [ ]:
admissions=get_pd(database_file, database_loc, ids, admissions)